botName: Chloe

openAI:
  apiKey: sk-xxxXXXXxxXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXXX
  model: gpt-3.5-turbo
  contextTimeout: 300

gemini:
  apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxx_yyy_zzzzzzz

telegram:
  botToken: 1234567890:ABCxxXXXXXXXXXXXXXXXX0XXXXXXXXXXXXX
  escapeText: false
  parseMode: Markdown

system:
  whitelistEnabled: true
  useGemini: false
