botName: Chloe

openAI:
  apiKey: sk-xxxXXXXxxXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXXX
  model: gpt-3.5-turbo
  contextTimeout: 300

telegram:
  botToken: 1234567890:ABCxxXXXXXXXXXXXXXXXX0XXXXXXXXXXXXX

gemini:
  apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxx_yyy_zzzzzzz

system:
  whitelistEnabled: true
  useGemini: true
